# Generated by Django 4.0 on 2021-12-20 23:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
